package handlers

import (
	"database/sql"
	"encoding/json"
	"log"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"github.com/jmoiron/sqlx"
	"github.com/sherpaurgen/garagesale/internal/product"
)

// type Product struct {
// 	ID          string    `db:"product_id" json:"id"`
// 	Name        string    `db:"name" json:"name"`
// 	Cost        int       `db:"cost" json:"cost"`
// 	Quantity    int       `db:"quantity" json:"quantity"`
// 	DateCreated time.Time `db:"date_created" json:"date_created"`
// 	DateUpdated time.Time `db:"date_updated" json:"date_updated"`
// }

// sqlx gives additional power like Marshal database rows into structs (with embedded struct support), maps, and slices
// rows to structs
type ProductService struct {
	DB  *sqlx.DB
	Log *log.Logger
}

func (p *ProductService) List(w http.ResponseWriter, req *http.Request) {
	list := []product.Product{} //initialize empty list other wise it will return nil which is fine but difficult for frontend to parse json, doing this will return empty list []
	const q = `SELECT * FROM products`
	err := p.DB.Select(&list, q)

	if err != nil && err != sql.ErrNoRows {
		w.WriteHeader(http.StatusInternalServerError)
		p.Log.Println("Error querying db:", err)
		return
	}

	data, err := json.Marshal(list)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		p.Log.Println("Marshalling error:", err)
		return
	}
	w.Header().Set("content-type", "application/json; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	if _, err := w.Write(data); err != nil {
		p.Log.Println("Error writing to responsebody ", err)
	}
}

func (p *ProductService) GetProduct(w http.ResponseWriter, req *http.Request) {
	id := chi.URLParam(req, "id")
	//prod := []Product{}
	var prod product.Product
	const q = `SELECT product_id,name,cost,quantity,date_updated,date_created FROM products where product_id= $1`
	//initialize a single Product
	err := p.DB.Get(&prod, q, id)

	if err != nil && err != sql.ErrNoRows {
		w.WriteHeader(http.StatusInternalServerError)
		p.Log.Println("Error querying db:", err)
		return
	}

	data, err := json.Marshal(prod)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		p.Log.Println("Marshalling error:", err)
		return
	}
	w.Header().Set("content-type", "application/json; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	if _, err := w.Write(data); err != nil {
		p.Log.Println("Error writing to responsebody ", err)
	}
}

// handler to decode post req for creating new product
func (p *ProductService) CreateProduct(w http.ResponseWriter, req *http.Request) {
	var newprod product.NewProduct
	// var prod product.Product

	//product.NewProduct is a intermediate struct withoud autogenerated field like uuid, date updated created which dont have to be sent by client
	err := json.NewDecoder(req.Body).Decode(&newprod)
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		p.Log.Println(err)
		return
	}
	prod := product.Product{
		ID:          uuid.New().String(),
		Name:        newprod.Name,
		Cost:        newprod.Cost,
		Quantity:    newprod.Quantity,
		DateCreated: time.Now(),
		DateUpdated: time.Now(),
	}

	const q = `INSERT INTO products (product_id,name,cost,quantity,date_created,date_updated)
VALUES ($1,$2,$3,$4,$5,$6)`
	//data is inserted to db here
	_, err = p.DB.Exec(q, prod.ID, prod.Name, prod.Cost, prod.Quantity, prod.DateCreated, prod.DateUpdated)
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		p.Log.Println("error inserting product to db:", err)
		return
	}
	data, err := json.Marshal(prod)

	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		p.Log.Println("Error marshalling createdProduct:", err)
		return
	}
	w.Header().Set("content-type", "application/json; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	if _, err := w.Write(data); err != nil {
		p.Log.Println("Error writing createProd to responsebody ", err)
	}

}
